"""
DB-to-Excel mapping configuration for Excel write-back.

Each entry maps a database table to its corresponding Excel workbook,
worksheet, header row, primary key fields, and column name mapping.

To add a new table: add an entry to EXCEL_MAPPING with the same structure.
"""

EXCEL_MAPPING = {
    "notas": {
        "excel_file": "PortfolioDigital_Master.xlsm",
        "sheet_name": "Notas",
        "header_row": 4,
        "pk_fields": ["portfolio_id", "fecha", "registrado_por"],
        "column_mapping": {
            "portfolio_id": "Portfolio ID",
            "registrado_por": "Registrado Por",
            "fecha": "Fecha",
            "nota": "Nota",
        },
    },
    "hechos": {
        "excel_file": "PortfolioDigital_Master.xlsm",
        "sheet_name": "Hechos",
        "header_row": 3,
        "pk_fields": ["id_hecho"],
        "insert_pk_reconcile": {
            "pk_field": "id_hecho",
            "strategy": "excel_max_plus_one",
        },
        "column_mapping": {
            "id_hecho": "ID",
            "portfolio_id": "Portfolio ID",
            "partida_presupuestaria": "Partida Presupuestaria",
            "importe": "Importe",
            "estado": "Estado",
            "fecha": "Fecha",
            "importe_ri": "Importe RI",
            "importe_re": "Importe RE",
            "notas": "Notas",
            "racional": "Racional",
            "calidad_estimacion": "Calidad Estimación",
        },
    },
    "etiquetas": {
        "excel_file": "PortfolioDigital_Master.xlsm",
        "sheet_name": "Etiquetas",
        "header_row": 3,
        "pk_fields": ["portfolio_id", "etiqueta"],
        "column_mapping": {
            "portfolio_id": "Portfolio ID",
            "etiqueta": "Etiqueta",
            "valor": "Valor",
            "fecha_modificacion": "Fecha Modificación",
            "origen_registro": "Origen Registro",
            "comentarios": "Comentarios",
        },
    },
    "acciones": {
        "excel_file": "PortfolioDigital_Master.xlsm",
        "sheet_name": "Acciones",
        "header_row": 3,
        "pk_fields": ["portfolio_id", "siguiente_accion"],
        "column_mapping": {
            "portfolio_id": "Portfolio ID",
            "siguiente_accion": "Siguiente Acción",
            "siguiente_accion_comentarios": "Siguiente Acción Comentarios",
            "comentarios": "Comentarios",
        },
    },
    "datos_descriptivos": {
        "excel_file": "PortfolioDigital_Master.xlsm",
        "sheet_name": "Datos descriptivos",
        "header_row": 3,
        "pk_fields": ["portfolio_id"],
        "insert_blocked": True,
        "column_mapping": {
            "portfolio_id": "Portfolio ID",
            "nombre": "Nombre",
            "unidad": "Unidad",
            "origen": "Origen",
            "digital_framework_level_1": "Digital Framework Level 1",
            "prioridad_descriptiva_bi": "Prioridad Descriptiva BI",
            "priorizacion": "Priorización",
            "tipo_proyecto": "Tipo Proyecto",
            "referente_bi": "Referente BI",
            "referente_b_unit": "Referente B Unit",
            "referente_enabler_ict": "Referente Enabler (ICT)",
            "it_partner": "IT Partner",
            # "codigo_jira": "Codigo Jira", # this field does not exist
            "cluster": "Cluster 2025",
            "tipo_agrupacion": "Tipo Agrupación",
        },
    },
    "informacion_economica": {
        "excel_file": "PortfolioDigital_Master.xlsm",
        "sheet_name": "Información Económica",
        "header_row": 3,
        "pk_fields": ["portfolio_id"],
        "column_mapping": {
            "portfolio_id": "Portfolio ID",
            "cini": "CINI",
            "capex_opex": "(CAPEX/OPEX)",
            "fecha_prevista_pes": "Fecha Prevista PES",
            "wbe": "WBE",
            "cluster": "Cluster",
            "finalidad_budget": "Finalidad Budget",
            "proyecto_especial": "Proyecto Especial",
            "clasificacion": "Clasificación",
            "tlc": "TLC",
            "tipo_inversion": "Tipo Inversión",
            "observaciones": "Observaciones",
        },
    },
    "estado_especial": {
        "excel_file": "PortfolioDigital_Master.xlsm",
        "sheet_name": "Estado Especial",
        "header_row": 3,
        "pk_fields": ["portfolio_id"],
        "column_mapping": {
            "portfolio_id": "Portfolio ID",
            "estado_especial": "Estado Especial",
            "fecha_modificacion": "Fecha Modificación",
            "comentarios": "Comentarios",
        },
    },
    "impacto_aatt": {
        "excel_file": "PortfolioDigital_Master.xlsm",
        "sheet_name": "Impacto AATT",
        "header_row": 3,
        "pk_fields": ["portfolio_id"],
        "column_mapping": {
            "portfolio_id": "Portfolio ID",
            "tiene_impacto_en_aatt": "Tiene Impacto en AATT",
            "afecta_a_ut_red_mt_bt": "Afecta a UT Red MT BT",
            "afecta_om_cc": "Afecta O&M-CC",
            "afecta_pm": "Afecta P&M",
            "afecta_hseq": "Afecta HSEQ",
            "afecta_inspecciones": "Afecta Inspecciones",
            "afecta_at": "Afecta AT",
            "comentarios": "Comentarios"
        },
    },
    "justificaciones": {
        "excel_file": "PortfolioDigital_Master.xlsm",
        "sheet_name": "Justificaciones",
        "header_row": 3,
        "pk_fields": ["portfolio_id", "tipo_justificacion"],
        "column_mapping": {
            "portfolio_id": "Portfolio ID",
            "tipo_justificacion": "Tipo Justificación",
            "valor": "Valor",
            "fecha_modificacion": "Fecha Modificación",
            "origen_registro": "Origen Registro",
            "comentarios": "Comentarios",
        },
    },
    "descripciones": {
        "excel_file": "PortfolioDigital_Master.xlsm",
        "sheet_name": "Descripciones",
        "header_row": 3,
        "pk_fields": ["portfolio_id", "tipo_descripcion"],
        "column_mapping": {
            "portfolio_id": "Portfolio ID",
            "tipo_descripcion": "Tipo Descripción",
            "descripcion": "Descripción",
            "fecha_modificacion": "Fecha Modificación",
            "origen_registro": "Origen Registro",
            "comentarios": "Comentarios",
        },
    },
    "ltp": {
        "excel_file": "PortfolioDigital_Master.xlsm",
        "sheet_name": "LTP",
        "header_row": 3,
        "pk_fields": ["portfolio_id", "tarea"],
        "column_mapping": {
            "portfolio_id": "Portfolio ID",
            "responsable": "Responsable",
            "tarea": "Tarea",
            "siguiente_accion": "Siguiente Acción",
            "fecha_creacion": "Fecha Creación",
            "estado": "Estado",
            "comentarios": "Comentarios",
        },
    },
    "wbes": {
        "excel_file": "PortfolioDigital_Master.xlsm",
        "sheet_name": "WBEs",
        "header_row": 3,
        "pk_fields": ["portfolio_id", "anio", "wbe_pyb"],
        "column_mapping": {
            "portfolio_id": "Portfolio ID",
            "anio": "Ano Presupuesto",
            "wbe_pyb": "WBE PyB",
            "descripcion_pyb": "Descripción",
            "wbe_can": "WBE CAN",
            "descripcion_can": "Descripción2",
        },
    },
    "dependencias": {
        "excel_file": "PortfolioDigital_Master.xlsm",
        "sheet_name": "Dependencias",
        "header_row": 3,
        "pk_fields": ["portfolio_id", "descripcion_dependencia"],
        "column_mapping": {
            "portfolio_id": "Portfolio ID",
            "descripcion_dependencia": "Descripción Dependencia",
            "fecha_dependencia": "Fecha Dependencia",
            "comentarios": "Comentarios",
        },
    },
    "grupos_iniciativas": {
        "excel_file": "PortfolioDigital_Master.xlsm",
        "sheet_name": "Grupos Iniciativas",
        "header_row": 3,
        "pk_fields": ["portfolio_id_grupo", "portfolio_id_componente"],
        "column_mapping": {
            "portfolio_id_grupo": "Portfolio ID Grupo",
            "portfolio_id_componente": "Portfolio ID Componente",
            "nombre_grupo": "Nombre Grupo",
            "tipo_agrupacion_grupo": "Tipo Agrupación Grupo",
            "tipo_agrupacion_componente": "Tipo Agrupación Componente",
        },
    },
}
