export const CHANGELOG = [
  {
    version: '0.070',
    feature: 70,
    title: 'Mejoras UI y System Prompt del Chatbot',
    summary: 'Siete mejoras: (1) Fix del sticky header en Detail — el sidebar lateral y los encabezados de sección ya no quedan ocultos detrás del header sticky más alto (offsets actualizados de top-36/scroll-mt-36 a top-44/scroll-mt-44). (2) Etiquetas de eje vertical en gráficos de barras del Dashboard — el ancho del eje Y se calcula dinámicamente midiendo el texto real con canvas.measureText, garantizando que las etiquetas siempre sean legibles sin recortes. (3) Fix de dropdowns de filtros del Dashboard — los desplegables ya no quedan recortados por el contenedor colapsable (overflow-visible cuando está expandido). (4) System prompt del chatbot: campo importe_YYYY como campo por defecto para consultas financieras genéricas (budget, sm200, aprobado y facturación solo si se piden explícitamente). (5) System prompt del chatbot: nueva regla "fuera de budget" — filtra por campo cluster con patrones extrabudget/fuera de budget; el campo cluster_2025_antes_de_19062025 queda marcado como deprecado. (6) QuickSearch: mejora visual con columna de portfolio_id más ancha, badge "ID" para resultados coincidentes por ID, y placeholder actualizado indicando búsqueda parcial. (7) El campo cluster_2025_antes_de_19062025 queda oficialmente deprecado — no se usa en ningún cálculo, consulta ni visualización.',
  },
  {
    version: '0.069',
    feature: 69,
    title: 'Cambios en Datos Relevantes: Cierre Económico y Activo Ejercicio',
    summary: 'Dos cambios en datos_relevantes: (1) El campo iniciativa_cerrada_economicamente ahora muestra "Cerrado en año YYYY" en lugar de "Sí"/"No", extrayendo el año de la partida presupuestaria del hecho de cierre económico. (2) Nuevo campo activo_ejercicio_actual ("Si"/"No") que indica si la iniciativa está activa en el ejercicio actual (no cerrada económicamente y con importe en el año en curso). Ambos campos propagados a: cálculo management, búsqueda (filtros dinámicos y columna seleccionable), dashboard (filtro actualizado), detalle (sección Datos Descriptivos), exportación Excel ("Activo en el ejercicio actual"), y agente IA (system prompt actualizado).',
  },
  {
    version: '0.068',
    feature: 68,
    title: 'Mejoras Múltiples: Chat, Búsqueda, Detalle y Gráficos',
    summary: 'Cuatro mejoras en la plataforma: (1) Fix del botón "Nueva Conversación" en el chat — corregida condición de carrera que impedía limpiar correctamente el contexto cuando se abortaba una petición en curso. (2) Filtro de iniciativas canceladas en Search — nuevo checkbox "Incluir Iniciativas Canceladas" (por defecto desactivado) que excluye iniciativas con estado "Cancelada"; se resetea al limpiar filtros. (3) Badges de estado en cabecera de Detail — el header sticky ahora muestra estado de la iniciativa (con color de parametros), tiene SM100, tiene SM200 e iniciativa aprobada como badges verdes/rojos siempre visibles al hacer scroll. (4) Orden de gráficos preservado — la herramienta generar_grafico del MCP server ya no ordena automáticamente los datos por valor; el agente IA controla el orden de las barras.',
  },
  {
    version: '0.067',
    feature: 67,
    title: 'Herramienta SQL Query para Agentes IA',
    summary: 'Nueva herramienta ejecutar_consulta_sql disponible tanto en el servidor MCP como en el chatbot web. Permite ejecutar consultas SQL SELECT de solo lectura contra la base de datos del portfolio. Incluye validación de seguridad centralizada (solo SELECT, sin inyección SQL, límite de filas), reporte transparente del SQL ejecutado con explicación, y contexto de esquema completo en las descripciones de herramientas. Nuevo endpoint POST /api/v1/sql/execute en el backend con validación via sqlparse.',
  },
  {
    version: '0.066',
    feature: 66,
    title: 'Visualización de Gráficos en Agentes IA',
    summary: 'Nueva herramienta generar_grafico disponible tanto en el servidor MCP como en el chatbot web. Genera gráficos PNG (barras, barras horizontales, tarta/donut, líneas, barras apiladas) a partir de datos del portfolio usando matplotlib. Dos modos: consulta automática (agrupa datos_relevantes por campo) o directo (datos pre-obtenidos). El chatbot sugiere proactivamente visualizaciones cuando los datos agregados contienen 3+ grupos. Las imágenes se sirven desde un nuevo endpoint GET /api/v1/charts/{id}.png y se renderizan inline en el chat. Paleta de colores consistente con el frontend.',
  },
  {
    version: '0.065',
    feature: 65,
    title: 'Mejoras del Chatbot: Persistencia, Links, Razonamiento, Supuestos',
    summary: 'Cuatro mejoras en el chatbot: (1) Persistencia de conversación — la conversación se mantiene al navegar entre páginas gracias a un ChatContext elevado sobre el router. (2) Links clicables de portfolio_id — los IDs de portfolio en respuestas (tablas, listas, párrafos) son ahora enlaces navegables a la página de detalle. (3) Acordeón de razonamiento — el texto de "thinking" del asistente (antes descartado) se captura y muestra en un acordeón colapsable "Razonamiento del asistente". (4) Transparencia en supuestos — el system prompt ahora instruye al modelo a incluir una sección "Supuestos aplicados" al final de respuestas con análisis de datos.',
  },
  {
    version: '0.064',
    feature: 64,
    title: 'Mejoras Múltiples: Filtros, Campos Calculados, Chatbot UI, Colores Paramétricos',
    summary: 'Trece mejoras en la plataforma: (1) Corrección del filtro de texto libre en Search — los filtros de columna ya permiten escribir texto completo (bug de 1 carácter). (2-4) Tres nuevos campos calculados en datos_relevantes: Estado SM100, Estado SM200 e Iniciativa Aprobada, derivados del estado de la iniciativa, con exportación a Excel. (5) Nuevos campos expuestos como columnas/filtros en Search y en la sección Datos Descriptivos del Detail. (6) Rediseño del chatbot con interfaz minimalista y futurista: gradientes, frosted glass, avatares con glow. (7) Historial de comandos en el chatbot (flecha arriba/abajo). (8) Sistema de colores paramétricos: la tabla parametros incluye columna color, con 21 colores de estado precargados y gestión CRUD desde Parametricas. (9-11) Mejoras en el system prompt del agente IA: exclusión de iniciativas canceladas, importes del año en curso por defecto, e inyección de fecha actual.',
  },
  {
    version: '0.063',
    feature: 63,
    title: 'Asistente IA del Portfolio',
    summary: 'Chat conversacional con IA integrado en la aplicación. El asistente usa la API de Anthropic con tool use para consultar los datos del portfolio a través de 9 herramientas (buscar iniciativas, contar, totalizar importes, obtener detalles, listar tablas, etc.). Arquitectura: Frontend (ChatPage) → SSE POST /agent/chat → Backend (orchestrator) → Anthropic API → Agent Tools → FastAPI REST API → SQLite. Incluye streaming de respuestas via SSE, renderizado de Markdown con tablas, y nueva entrada "Asistente IA" en el navbar.',
  },
  {
    version: '0.062',
    feature: 62,
    title: 'Mobile & Accessibility Improvements',
    summary: 'Eight enhancements across mobile UX, accessibility, and data grid capabilities: (1) GlobalSearch in mobile menu — "Buscar" button in hamburger menu opens search overlay. (2) Enhanced focus rings — standardized ring-ring ring-offset-2 across all form inputs and interactive elements, plus forced-colors media query for Windows High Contrast. (3) Page-specific loading skeletons — Dashboard, Search, Detail, and Report pages each show layout-matching skeleton screens during lazy loading. (4) Card-based mobile search view — toggle between table and card grid views, with initiative cards showing key data and persisted preference. (5) Mobile detail navigation — floating action button + bottom sheet for section navigation on mobile/tablet. (6) Cross-report navigation — dropdown menu per report row to jump to related reports pre-filtered by portfolio_id. (7) Column-level DataGrid filtering — per-column filter popovers (text/select/range) for client-side filtering on search results. (8) Row grouping in DataGrid — group-by dropdown to organize rows by Estado, Unidad, Cluster, Digital Framework, or Tipo with collapsible group headers.',
  },
  {
    version: '0.061',
    feature: 61,
    title: 'Detail Page Advanced Features: Section History, Related Initiatives, Activity Timeline',
    summary: 'Three detail page improvements: (1) Section edit history — clock icon button on each editable section header opens a modal showing all transacciones_json records for that entity type, with expandable JSON diff view of changes and primary keys. (2) Related initiatives widget — new accordion section showing up to 20 initiatives that share the same cluster, unidad, or etiquetas, powered by a new GET /portfolio/{pid}/related backend endpoint with colored reason badges. (3) Unified activity timeline — new accordion section merging hechos, notas, and transacciones_json into a single chronological timeline with type icons, badges, and "load more" pagination via a new GET /portfolio/{pid}/timeline endpoint.',
  },
  {
    version: '0.060',
    feature: 60,
    title: 'Dashboard Advanced Features: KPI Trends, Chart Export, Dynamic Landing Stats',
    summary: 'Three dashboard improvements: (1) KPI trend indicators — financial KPI cards (Importe Total, Budget) show year-over-year delta arrows with percentage change (green up/red down) computed from existing multi-year data. (2) Chart export as PNG — each bar chart card has a download button that captures the chart as a 2x-resolution PNG image using html2canvas. (3) Dynamic landing page stats — HeroSection stats now fetched from a new GET /api/v1/stats/overview endpoint instead of hardcoded values, with skeleton loading and fallback on error.',
  },
  {
    version: '0.059',
    feature: 59,
    title: 'Report Enhancements: Aggregation Footer, Date Presets, Empty State, Templates',
    summary: 'Four report page improvements across all GenericReportPage-based reports: (1) Aggregation footer — sticky table footer row showing sum/count/avg totals for configured numeric columns on the current page, with "Totales (página)" label. (2) Date range presets — quick-select pill buttons (last 7/30 days, this month, quarter, year) for date range filter pairs, using dateRangeGroup pairing. (3) Improved empty state — filter-aware empty state showing active filter badges with values and contextual suggestions to adjust filters. (4) Saved report templates — save, load, and delete named filter/column/sort configurations per report (max 10, stored in localStorage) via dropdown menu.',
  },
  {
    version: '0.058',
    feature: 58,
    title: 'UI Components Batch',
    summary: 'Four UI improvements: (1) DatePicker calendar component with react-day-picker for date fields in entity forms, replacing native HTML5 date inputs. (2) Dialog size variants — sm, md, lg, xl, and full — applied to all dialog consumers. (3) Changelog search filter and collapsible version groups (ranges of 10) on the landing page. (4) Reusable EmptyState component for empty data areas across Search, Reports, and InitiativeDrawer.',
  },
  {
    version: '0.057',
    feature: 57,
    title: 'Detail Page: Sidebar Search, Sortable Tables, Section Export',
    summary: 'Three Detail page improvements: (1) Section search in sidebar — text input at the top of the DetailNav sidebar filters section links by name with accent-insensitive matching and clear button. (2) Sortable SimpleTable columns — clickable column headers cycle through ascending, descending, and unsorted states with type-aware comparison (numeric, date, text) and nulls-last behavior. (3) Per-section CSV export — download button in accordion headers for 10 SimpleTable sections exports data as semicolon-separated CSV with UTF-8 BOM for Excel compatibility.',
  },
  {
    version: '0.056',
    feature: 56,
    title: 'Search Page Enhancements: Saved Searches, Filter Chips, Cross-Page Selection',
    summary: 'Five Search page improvements: (1) Saved Searches — name, save, load, and delete filter configurations from a dropdown in the filter panel header (max 20, stored in localStorage). (2) Filter Chips — active filters displayed as removable chip/badge elements between the filter panel and data grid; click X to remove individual filters. (3) Export Sort Fix — exports now respect the current sort order, not just column selection. (4) Persistent Row Selection — selected rows persist across page changes; only cleared on filter/sort changes. Selection count shown in toolbar. (5) Portfolio ID Paste Validation — pasted IDs validated against SPA_YY_NNN format with amber warning for mismatches.',
  },
  {
    version: '0.055',
    feature: 55,
    title: 'Dashboard Polish: Tooltip Percentages, Label Tooltips, Collapsible Filters',
    summary: 'Three dashboard UI improvements: (1) Chart tooltips now show percentage of total alongside the value (e.g., "42 (15.3% del total)") for both count and importe charts. (2) Truncated Y-axis labels in bar charts show the full text via native browser tooltip on hover. (3) FilterBar is wrapped in a collapsible panel with a toggle button, active filter count badge when collapsed, and state persisted to localStorage.',
  },
  {
    version: '0.054',
    feature: 54,
    title: 'Navigation Enhancements',
    summary: 'Four navigation improvements: (1) Breadcrumb navigation bar between Navbar and content on all protected routes, with route metadata and dynamic parent chain (supports location.state.from for contextual parents). (2) Context-aware back button in DetailHeader — shows "Volver a Busqueda", "Volver a Dashboard", etc. based on where you navigated from, with graceful fallback to browser history. (3) Recent Initiatives dropdown in Navbar tracks last 10 visited initiatives in localStorage with quick navigation and clear history. (4) Deep-linkable detail sections via URL hash — scroll syncs hash, direct links auto-expand and scroll to the target section.',
  },
  {
    version: '0.053',
    feature: 53,
    title: 'Quick Wins: Searchable Dropdowns, Persistent Filters, Collapse/Expand All, Landing CTA',
    summary: 'Four UI polish improvements: (1) All MultiSelect dropdowns across Search, Dashboard, and Report filter panels now support type-ahead search for faster option selection. (2) Search page FilterPanel collapsed/expanded state persists to localStorage across page reloads. (3) Detail page gains Expand All/Collapse All buttons with centralized accordion state management; empty sections are consolidated into a summary panel at the bottom with inline create buttons for CRUD-enabled entities; sidebar nav hides empty sections. (4) Landing page hero section adds auth-conditional CTA button: "Ir al Dashboard" for signed-in users, "Iniciar Sesión" for guests.',
  },
  {
    version: '0.051',
    feature: 51,
    title: 'MCP Server for AI-Powered Portfolio Queries',
    summary: 'New MCP (Model Context Protocol) server module that provides read-only access to all portfolio data for AI agents. Acts as an HTTP client of the existing FastAPI backend, translating 9 MCP tools into API calls. Tools include: buscar_iniciativas (search), obtener_iniciativa (full detail), contar_iniciativas (count by dimension), totalizar_importes (aggregate financials), obtener_documentos (AI summaries), listar_tablas/describir_tabla/obtener_valores_campo (schema discovery). All tool descriptions in Spanish. Supports stdio (Claude Desktop/Code) and SSE (remote) transports.',
  },
  {
    version: '0.050',
    feature: 50,
    title: 'UI Improvements: Color Themes, Collapsed Sections, Spanish i18n',
    summary: 'Three UI enhancements: (1) Color theme selector with 6 themes (Clásico, Pizarra, Esmeralda, Ámbar, Rosa, Violeta) — 4 high-contrast options with vivid accent colors for section titles, buttons, and accordions. Themes are orthogonal to dark/light mode and persist in localStorage. (2) Five Detail page sections (Beneficios, Etiquetas, WBEs, Transacciones, Transacciones JSON) now collapsed by default to reduce clutter. (3) Comprehensive Spanish language review: translated remaining English UI text (combobox, dialog, sheet, aria-labels) and fixed 70+ instances of missing accents (tildes) across 30+ files.',
  },
  {
    version: '0.049',
    feature: 49,
    title: 'Trabajos Menu: Run Management Commands from Browser',
    summary: 'New Trabajos dropdown menu in the navbar to trigger management CLI operations (Proceso completo, Escanear documentos, Sumarizar documentos) directly from the web application. Backend streams command output via SSE (Server-Sent Events) using FastAPI StreamingResponse. Frontend ConsoleDialog displays real-time terminal-like output with dark background, monospace font, auto-scroll, color-coded stdout/stderr, status badges, and elapsed time. Singleton guard ensures only one job runs at a time.',
  },
  {
    version: '0.048',
    feature: 48,
    title: 'Management .env Refactor',
    summary: 'Refactored management module .env configuration: base directories (EXCEL_SOURCE_DIR, EXCEL_OUTPUT_DIR) defined once with filenames composed at runtime, eliminating path repetition. Renamed variables for consistency (DATOS_RELEVANTES_*, DOCUMENTOS_EXPORT_*, DOCUMENTOS_ITEMS_EXPORT_*). Removed deprecated WINDOWS_EXCEL_PATH and copy_excel_sources.sh WSL script.',
  },
  {
    version: '0.047',
    feature: 47,
    title: 'Documentos Processing Improvement',
    summary: 'Streamlined documentos pipeline: documentos table now migrated from Excel, new documentos_items table expands resumen_documento JSON into queryable rows with export/import support. CLI renamed from main.py to manage.py, full_calculation_datos_relevantes renamed to complete_process with scan_documents added to the pipeline. Frontend: Informe Documentos gains initiative side drawer, Detail page Documentos section shows expandable rows with ruta/dates/tokens details, and estado_proceso_documento rendered as colored tags throughout.',
  },
  {
    version: '0.046',
    feature: 46,
    title: 'Document Summary Viewer Modals',
    summary: 'Two new viewer modals for LLM-generated document summaries. JSON viewer modal displays syntax-highlighted raw JSON with color-coded keys, strings, numbers, and booleans. Formatted summary modal renders JSON as clean HTML with section headings, paragraphs, and bullet lists. Both modals include SharePoint document links. Integrated into Detail page Documentos section and Informe Documentos report page.',
  },
  {
    version: '0.045',
    feature: 45,
    title: 'Summarize Documentos Enhancements',
    summary: 'Enhanced summarize_documentos command with --portfolio-ids, --reprocess, and --json-output-to-console CLI flags. Default model changed to Haiku for cost optimization. Per-document token tracking stored in database and logged. DOCX reader now extracts Word tables (cover page metadata). Filename passed as LLM context for better title extraction. Improved prompts for titulo_documento, escrito_por, verificado_por fields. Error resilience ensures batch never stops. Documentos table protected via PRESERVED_TABLES. Excel export formats dates as DD/MM/YYYY.',
  },
  {
    version: '0.044',
    feature: 44,
    title: 'LLM Document Summarization',
    summary: 'New summarize_documentos CLI command in the management module that processes pending documents using Claude AI. Reads PDF, DOCX, and TXT files, generates structured JSON summaries per document type (SM100, SM200, generic), stores results in the documentos table, and exports to Excel. Extensible LLM provider pattern for future integration with other AI models.',
  },
  {
    version: '0.043',
    feature: 43,
    title: 'Document Management: Scanner, Detail Section & Report',
    summary: 'New documentos table linking documents (SM100, SM200, Approval Form) to initiatives. Management CLI scan_documents command discovers documents from configured OneDrive folders with subfolder and flat scanning modes. Detail page shows Documentos accordion section with SharePoint links. New Informe Documentos report page with tipo/estado filters and clickable file links.',
  },
  {
    version: '0.042',
    feature: 42,
    title: 'Etiquetas Destacadas: Highlighted Tags & Parametricas Menu',
    summary: 'New parametric table etiquetas_destacadas with CRUD management page. Parametricas navigation becomes a dropdown menu with Etiquetas Destacadas and Parametricas subitems. Initiatives with highlighted etiquetas show colored badges in the Detail page header and Initiative side drawer.',
  },
  {
    version: '0.041',
    feature: 41,
    title: 'UI Improvements: Global Search, LTP Modal, New Reports, Drawer Fixes',
    summary: 'Global search (Ctrl+Shift+F) in top menu for finding initiatives by ID or name. LTP quick-edit modal in Search page with full CRUD. Initiative side drawer now shows data from all pages including reports. Datos Descriptivos delete disabled. LTP report defaults to Pendiente filter. Four new report pages: Justificaciones, Dependencias, Descripciones, and Notas with side drawer and detail links.',
  },
  {
    version: '0.040',
    feature: 40,
    title: 'UI Polish: Sticky Headers, Drawer Buttons, Estado Tags Across Reports',
    summary: 'Sticky table headers across Search, Hechos, LTPs, Acciones, Etiquetas, Transacciones, and Transacciones JSON pages. Side drawer quick-view button added as dedicated column before Portfolio ID in Search, Hechos, LTPs, and Acciones. Estado columns render as colored tags in Search and Acciones. LTP estado tags show green/red for Completado/Pendiente. Initiative drawer shows Notas, Justificaciones, Descripciones, and Dependencias tables. EstadoTag components have consistent minimum width with centered text.',
  },
  {
    version: '0.039',
    feature: 39,
    title: 'Excel Write-Back Resilience & Debug Logging',
    summary: 'Excel write-back now detects and reuses already-open workbooks instead of failing, leaving them open for the user after saving. Added comprehensive debug-level logging throughout the write-back process.',
  },
  {
    version: '0.038',
    feature: 38,
    title: 'UI Improvements: Tags, Expandable Rows, Side Drawer, Parametricas CRUD',
    summary: 'Estado fields now display as colored tags across Hechos, LTP, Etiquetas reports and Detail page. Hechos report has expandable rows and side drawer. LTP report rows expand to show comentarios. New Parametricas admin page with full CRUD.',
  },
  {
    version: '0.037',
    feature: 37,
    title: 'Parametric Tables & Dropdown Selectors',
    summary: 'Added parametric values table populated from migration data for 14 codified fields, with API endpoint and dropdown selectors in all entity edit/create forms.',
  },
  {
    version: '0.036',
    feature: 36,
    title: 'Landing Page Redesign & Changelog',
    summary: 'Redesigned landing page with simplified hero section and changelog showing all implemented features with version tracking.',
  },
  {
    version: '0.035',
    feature: 35,
    title: 'Detail Page Visual Polish & Badges',
    summary: 'Added data existence indicators to sidebar navigation with count badges for 1:N sections and dots for 1:1 sections.',
  },
  {
    version: '0.034',
    feature: 34,
    title: 'Optimize Excel Write-Back Bulk Reads',
    summary: 'Replaced cell-by-cell COM calls with single bulk-read per sheet cached in memory, reducing COM interop overhead.',
  },
  {
    version: '0.033',
    feature: 33,
    title: 'Excel Primary Key Columns & Full Transaction Display',
    summary: 'Added clave_primaria_excel field and composite keys for 1:N entities, displaying execution dates and Excel PKs in transaction details.',
  },
  {
    version: '0.032',
    feature: 32,
    title: 'Excel Write-Back Schema Mapping & Entity Configuration',
    summary: 'Configured Excel sheet mapping for all 12 entities with field mappings, primary key definitions, and header row detection.',
  },
  {
    version: '0.031',
    feature: 31,
    title: 'Search & Detail UX Improvements',
    summary: 'Added row selection checkboxes, bulk copy of portfolio IDs, paste normalization, and sticky sidebar navigation for detail pages.',
  },
  {
    version: '0.030',
    feature: 30,
    title: 'Excel Write-Back Error Handling & Recovery',
    summary: 'Implemented comprehensive error handling for Excel operations including cell validation, row locking, and transaction rollback.',
  },
  {
    version: '0.029',
    feature: 29,
    title: 'Transacciones JSON Excel Write-Back',
    summary: 'Integrated xlwings COM automation to sync database changes back to source Excel workbooks with row matching and reconciliation.',
  },
  {
    version: '0.028',
    feature: 28,
    title: 'Search Page Column Configuration & Persistence',
    summary: 'Implemented drag-and-drop column configurator with visible/available column separation and localStorage persistence.',
  },
  {
    version: '0.027',
    feature: 27,
    title: 'Cierre Economico Support: Calculated Estado Fields',
    summary: 'Added estado workflow fields for approval/execution tracking with multi-step validation and workflow-based field visibility.',
  },
  {
    version: '0.026',
    feature: 26,
    title: 'Dashboard Filter Improvements & Persistence',
    summary: 'Enhanced dashboard filters with 9 configurable dimensions, localStorage persistence, and real-time chart updates.',
  },
  {
    version: '0.025',
    feature: 25,
    title: 'Informe Reports: JSON Transacciones Report',
    summary: 'Added JSON transaction report with operation/entity filtering, error highlighting, and detailed audit review.',
  },
  {
    version: '0.024',
    feature: 24,
    title: 'Data Linkage: Related Entities Cross-References',
    summary: 'Established foreign key relationships across all 25 tables with consistent portfolio_id foreign key and relational integrity.',
  },
  {
    version: '0.023',
    feature: 23,
    title: 'CRUD Operations on Related Entities',
    summary: 'Implemented modal-based create/edit/delete workflows for entities via the transacciones_json system with change tracking.',
  },
  {
    version: '0.022',
    feature: 22,
    title: 'Detail Page: Portfolio Full Context View',
    summary: 'Created comprehensive detail page displaying all related entity sections in collapsible accordions with relationships.',
  },
  {
    version: '0.021',
    feature: 21,
    title: 'Search Page: Flexible Filtering & Data Grid',
    summary: 'Built search interface with 9 filters, 60+ configurable columns, drag-and-drop reordering, sorting, pagination, and export.',
  },
  {
    version: '0.020',
    feature: 20,
    title: 'JSON Processor: Database Change Application',
    summary: 'Created backend service to parse JSON transactions and apply database changes atomically with rollback on error.',
  },
  {
    version: '0.019',
    feature: 19,
    title: 'Transacciones JSON: Change Tracking & Audit Trail',
    summary: 'Implemented transaction audit system capturing JSON diffs of all changes with operation type and full lifecycle tracking.',
  },
  {
    version: '0.018',
    feature: 18,
    title: 'Informe Reports: Acciones, Etiquetas, Transacciones',
    summary: 'Added 3 additional report pages with consistent filter-and-grid pattern, localStorage persistence, and export.',
  },
  {
    version: '0.017',
    feature: 17,
    title: 'Informe Reports: Hechos & LTPs with Custom Layouts',
    summary: 'Created specialized Hechos report with date-range filtering and LTP report with responsable/estado filtering.',
  },
  {
    version: '0.016',
    feature: 16,
    title: 'Informe Reports: Framework, Cluster, Unidad, Priorizacion',
    summary: 'Implemented 4 configurable report pages with dynamic filter panels, column selection, and server-side pagination.',
  },
  {
    version: '0.015',
    feature: 15,
    title: 'Dashboard Sidebar Navigation & Detail Links',
    summary: 'Added sticky sidebar navigation for dashboard sections and integrated portfolio_id links throughout the application.',
  },
  {
    version: '0.014',
    feature: 14,
    title: 'Dashboard: KPIs, Charts & Drill-Down Navigation',
    summary: 'Built interactive dashboard with 4 KPI cards, chart pairs across 5 dimensions, filters, and drill-down to Search page.',
  },
  {
    version: '0.013',
    feature: 13,
    title: 'Frontend Skeleton: Layout, Routing & Authentication',
    summary: 'Created React SPA foundation with route-based code splitting, Clerk authentication, responsive layout, and theming.',
  },
  {
    version: '0.012',
    feature: 12,
    title: 'Calculated Fields: Advanced LookupCache & Service Layer',
    summary: 'Optimized calculated field computation with batch-based LookupCache, reducing SQL queries from thousands to dozens.',
  },
  {
    version: '0.011',
    feature: 11,
    title: 'FastAPI REST API Implementation',
    summary: 'Built complete REST API with 25 CRUD endpoints, paginated responses, flexible search, and Pydantic validation.',
  },
  {
    version: '0.010',
    feature: 10,
    title: 'Advanced Data Quality Validation',
    summary: 'Implemented comprehensive validation framework checking data integrity, type mismatches, and constraint violations.',
  },
  {
    version: '0.009',
    feature: 9,
    title: 'Application Modularization & Decoupling',
    summary: 'Refactored backend and frontend into feature-based modules with clear separation of concerns.',
  },
  {
    version: '0.008',
    feature: 8,
    title: 'Bulk Table Migrations: Database Extensions',
    summary: 'Automated bulk migration of support tables from Excel source with validation and error handling.',
  },
  {
    version: '0.007',
    feature: 7,
    title: 'Logging & Monitoring Infrastructure',
    summary: 'Implemented centralized logging system with module-specific loggers, file rotation, and configurable levels.',
  },
  {
    version: '0.006',
    feature: 6,
    title: 'Code Refactoring: Core Modules to Packages',
    summary: 'Reorganized monolithic scripts into proper Python package structure with module separation.',
  },
  {
    version: '0.005',
    feature: 5,
    title: 'Excel Data Export: datos_relevantes to Excel',
    summary: 'Implemented bulk export of computed datos_relevantes table back to Excel with status columns and audit trail.',
  },
  {
    version: '0.004',
    feature: 4,
    title: 'Configuration Management & Environment Setup',
    summary: 'Established environment-based configuration system using .env files with module-specific settings.',
  },
  {
    version: '0.003',
    feature: 3,
    title: 'Excel Workbook Migration: Reading & Normalization',
    summary: 'Implemented Excel-to-SQLite migration engine for 5 workbooks with data validation and formula error handling.',
  },
  {
    version: '0.002',
    feature: 2,
    title: 'Calculated Fields: datos_relevantes Denormalization',
    summary: 'Created computed table consolidating 60+ calculated fields from multiple source tables using cached lookups.',
  },
  {
    version: '0.001',
    feature: 1,
    title: 'Core System Architecture & Database Schema',
    summary: 'Established foundational architecture with SQLite database, 25 normalized tables, and complete system design.',
  },
]
